---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wuxin.
--- DateTime: 2019-11-14 18:12
---

local aes = require "resty.aes"
local str = require "resty.string"

local kong = kong


local ejuaes={}
ejuaes.PRIORITY=100
ejuaes.VERSION="1.0"



function ejuaes:header_filter(conf)
    -- 清空header中的content-length
    ngx.header.content_length=nil

end

function ejuaes:access(conf)
    if conf.keyDiscover then
        -- 中断本阶段后续过滤链，但不中断对下一个执行阶段的调用
        kong.response.exit(200,conf.key)
        return
    end
end

function ejuaes:body_filter(conf)

    -- 作为key曝露的接口; 打开此开关也可以达到不加密的效果
    if conf.keyDiscover then
        return
    end

    local data = ngx.arg[1]
    if data == '' then
        return
    end

    kong.log.err("data before aes... ", data )

    -- 加密
    local aes_128_cbc_with_iv = aes:new(conf.key, nil, aes.cipher(128,"cbc"), {iv=string.reverse(conf.key)})
    local encrypted = aes_128_cbc_with_iv:encrypt(data)
    local dataAfter = str.to_hex(encrypted)

    kong.log.err("data after aes... ", dataAfter )
    ngx.arg[1]=dataAfter

end



return ejuaes