---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wuxin.
--- DateTime: 2019-11-14 18:12
---

local aes = require "resty.aes"
local str = require "resty.string"

local kong = kong


local ejuaes={}
ejuaes.PRIORITY=100
ejuaes.VERSION="1.0"



function ejuaes:header_filter(conf)
    -- 清空header中的content-length
    ngx.header.content_length=nil
    
end




function ejuaes:body_filter(conf)

    -- 如果其它插件设置了这个标志，则表示无需再作任何处理
    if ngx.ctx.eju_dont_do_anything then
        return
    end

    local data = ngx.arg[1]
    if data == '' then
        return
    end

    kong.log.err("data before aes... ", data )

    -- 加密
    
    -- local aes_128_cbc_with_iv = aes:new(conf.key, nil, aes.cipher(128,"cbc"), {iv=string.reverse(conf.key)})
    -- local aes_128_cbc_with_iv = aes:new(conf.key, nil, aes.cipher(128,"ecb"), {iv=string.reverse(conf.key)})
    -- local encrypted = aes_128_cbc_with_iv:encrypt(data)
    -- local dataAfter = str.to_hex(encrypted)
    local dataAfter = str.to_hex(data)
    dataAfter = ngx.re.gsub(dataAfter,"c","x")
    dataAfter = ngx.re.gsub(dataAfter,"1","i")
    dataAfter = ngx.re.gsub(dataAfter,"7","q")
    

    kong.log.err("data after aes... ", dataAfter )
    
    ngx.arg[1]=dataAfter

end



return ejuaes